continents/urls.py
from django.contrib import admin
from django.urls import path
from continents.views import ContinentsView, ContinentDetailView

app_name = 'continents'

urlpatterns = [
    path('', ContinentsView.as_view(), name='home'),
    path('<translate>/', ContinentDetailView.as_view(), name='continent_detail'),
]

countries/urls.py
from django.contrib import admin
from django.urls import path
from countries.views import (
	CountryDetailView, 
	CountryDetailIDView, 
	CountrySearchView
)

app_name = 'countries'

urlpatterns = [
    path('search/<query>/', CountrySearchView.as_view(), name='country_search'),
    path('<int:pk>/', CountryDetailIDView.as_view(), name='country_id_detail'),
    path('<code>/', CountryDetailView.as_view(), name='country_code_detail'),
]

geographic/urls.py
from django.contrib import admin
from django.urls import path, include
from countries.views import HomeView, TagsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('tags/', TagsView.as_view(), name='tags'),
    path('continents/', include('continents.urls', namespace='continents')),
    path('countries/', include('countries.urls', namespace='countries')),
]

continents/models.py
from django.db import models


class Continent(models.Model):
	name = models.CharField(max_length=255)
	translate = models.CharField(max_length=255)
	color = models.CharField(max_length=255)

	def __str__(self):
		return self.name

countries/models.py
from django.db import models


class ActiveManager(models.Manager):
	def get_queryset(self):
		return super().get_queryset().filter(active=True)

class Country(models.Model):
	CODES_CHOICES	= (
		('colombia', 'CO'),
		('estados unidos', 'US'),
		('mexico', 'MX'),
		('argentina', 'AR'),
	)

	name = models.CharField(max_length=255)
	code = models.CharField(max_length=3, choices=CODES_CHOICES)
	continent = models.ForeignKey('continents.Continent', on_delete=models.CASCADE)
	active = models.BooleanField(default=True)
	active_manager = ActiveManager()
	objects = models.Manager()

	def __str__(self):
		return self.name

people/models.py
from django.db import models


class Person(models.Model):
	first_name = models.CharField(max_length=255)
	nationality = models.ManyToManyField('countries.Country')
	father = models.OneToOneField('self', on_delete=models.CASCADE, null=True)

continents/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from continents.models import Continent

class ContinentsView(TemplateView):
	template_name = 'continents/continents.html'

	def get_context_data(self, *args, **kwargs):

		america = {
			'name': 'américa', 
			'translation': 'america',
			'color': '#000000'
		}
		antartida = {
			'name': 'antártida', 
			'translation': 'antartica',
			'color': '#FFFF00'
		}
		europa = {
			'name': 'europa', 
			'translation': 'europa',
			'color': '#F1D142'
		}
		africa = {
			'name': 'áfrica', 
			'translation': 'africa',
			'color': '#F04261'
		}
		asia = {
			'name': 'asia', 
			'translation': 'asia',
			'color': '#EE65EE'
		}
		oceania = {
			'name': 'oceanía', 
			'translation': 'oceania',
			'color': '#EE65DD'
		}

		continents = [america, africa, asia, europa, oceania, antartida]

		return {'continents': continents}

class ContinentDetailView(DetailView):
	template_name = 'continents/continent_detail.html'
	model = Continent

	def get_context_data(self, *args, **kwargs):
		translate = kwargs['translate']
		return {'translate': translate}

countries/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from countries.models import Country


class HomeView(TemplateView):
	template_name = 'countries/home.html'

class TagsView(TemplateView):
	template_name = 'countries/tags.html'

class CountryDetailView(TemplateView):
	template_name = 'countries/country_detail.html'

	def get_context_data(self, *args, **kwargs):
		code = kwargs['code']
		return {'code': code}

class CountryDetailIDView(DetailView):
	template_name = 'countries/country_id.html'
	model = Country

class CountrySearchView(ListView):
	template_name = 'countries/search.html'
	model = Country

	def get_queryset(self):
		query = self.kwargs['query']
		return Country.objects.filter(name__contains=query)

people/views.py
from django.shortcuts import render

# Create your views here.

templates/continents/continent.html
<div>
	<h1 style="color: {{cont.color}}">{{cont.name|title}}</h1>
	<p>Ingles: {{cont.translation}}</p>
</div>

templates/continents/continent_detail.html
{% extends "countries/base.html" %}

{% block content %}
	<h1>Continents</h1>
	{% for cont in continents %}
		<hr />
			{% include "continent.html" %}
		<hr />
	{% endfor %}
{% endblock %}

templates/continents/continents.html
{% extends "countries/base.html" %}

{% block content %}
	<h1>Continents</h1>
	{% for cont in continents %}
		<hr />
			<a href="{% url 'continents:continent_detail' %}">{{cont.name}}</a>
		<hr />
	{% endfor %}
{% endblock %}

templates/countries/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}Geographic{% endblock %}</title>
</head>
<body>
	{% block content %}{% endblock %}
</body>
</html>

templates/countries/country.html
<h2>Name: {{ country.name|title }}</h2>
<p>Code: {{ country.code }}</p>
<p>Detail: <a href="{{country.detail_url}}">Detalle</a></p>

templates/countries/country_detail.html
{% extends "countries/base.html" %}

{% block content %}
	{% for country in countries %}
		{% if country.code == code %}
			{% include 'countries/country.html' %}
		{% endif %}
	{% endfor %}
{% endblock %}

templates/countries/country_id.html
{% extends "countries/base.html" %}

{% block content %}

{% include 'countries/country.html' with country=object %}

{% endblock %}

templates/countries/home.html
{% extends "countries/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
	{% for country in countries %}
		{% include "countries/country.html" %}
	{% endfor %}
	<p><a href="{% url "tags" %}">Ir a Tags</a></p>
	<p><a href="{% url "continents:home" %}">Ir a Continents</a></p>
	<p><a href="{% url "countries:country_id_detail" id=1 %}">Ir a Country 1</a></p>
{% endblock %}

templates/countries/search.html
{% extends "countries/base.html" %}

{% block content %}
	{% for country in object_list %}
		{% include "countries/country.html" %}
	{% endfor %}
{% endblock %}

templates/countries/tags.html
{% extends "countries/base.html" %}

{% block content %}

	{% comment %} texto prueba {% endcomment %}

	{% for country in countries %}
		<p>{{ country }}</p>

		{% if country.name == 'colombia' %}
			<p>Tierra querida</p>
		{% endif %}

		<p>lorem: {% lorem %}</p>
		<p>fecha actual: {% now "Y-m-d" %}</p>

		{% filter force_escape|lower %}
			%&$#$%^~~^`% TEXTO
		{% endfilter %}

	{% endfor %}

	<p>{{ "PRUEBA"|capfirst }}</p>
	<p>{{ 6|divisibleby:"3" }}</p>

{% endblock %}